"""add selected_product_id to fermentation_batches

Revision ID: 05c5566886bb
Revises: c1d2e3f4a5b6
Create Date: 2026-08-02 11:22:51.352633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c5566886bb'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fermentation_batches', sa.Column('selected_product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fermentation_batches', 'product_templates', ['selected_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fermentation_batches', type_='foreignkey')
    op.drop_column('fermentation_batches', 'selected_product_id')
    # ### end Alembic commands ###
