"""Initial migration to postgres

Revision ID: 4fbe94f9e549
Revises: 
Create Date: 2026-07-30 18:52:42.631702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbe94f9e549'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('processing_instructions', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('time_estimate_hours', sa.Float(), nullable=True),
    sa.Column('safety_warnings', sa.Text(), nullable=True),
    sa.Column('base_compatibility_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_templates_id'), 'product_templates', ['id'], unique=False)
    op.create_index(op.f('ix_product_templates_name'), 'product_templates', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('waste_diverted_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fermentation_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('waste_weight_kg', sa.Float(), nullable=True),
    sa.Column('water_liters', sa.Float(), nullable=True),
    sa.Column('sugar_kg', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('harvest_date', sa.DateTime(), nullable=True),
    sa.Column('final_volume_liters', sa.Float(), nullable=True),
    sa.Column('final_color', sa.String(), nullable=True),
    sa.Column('final_aroma_intensity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fermentation_batches_id'), 'fermentation_batches', ['id'], unique=False)
    op.create_table('fermentation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.DateTime(), nullable=True),
    sa.Column('aroma', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('gas_presence', sa.Boolean(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_status', sa.String(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['fermentation_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fermentation_logs_id'), 'fermentation_logs', ['id'], unique=False)
    op.create_table('product_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('recommended_products_json', sa.JSON(), nullable=True),
    sa.Column('selected_product_id', sa.Integer(), nullable=True),
    sa.Column('selection_date', sa.DateTime(), nullable=True),
    sa.Column('is_commercial_orientation', sa.Boolean(), nullable=True),
    sa.Column('business_analysis_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['fermentation_batches.id'], ),
    sa.ForeignKeyConstraint(['selected_product_id'], ['product_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_recommendations_batch_id'), 'product_recommendations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_product_recommendations_id'), 'product_recommendations', ['id'], unique=False)
    op.create_table('roadmap_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('product_template_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('steps_json', sa.JSON(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['fermentation_batches.id'], ),
    sa.ForeignKeyConstraint(['product_template_id'], ['product_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_progress_batch_id'), 'roadmap_progress', ['batch_id'], unique=False)
    op.create_index(op.f('ix_roadmap_progress_id'), 'roadmap_progress', ['id'], unique=False)
    op.create_index(op.f('ix_roadmap_progress_product_template_id'), 'roadmap_progress', ['product_template_id'], unique=False)
    op.create_index(op.f('ix_roadmap_progress_user_id'), 'roadmap_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_progress_user_id'), table_name='roadmap_progress')
    op.drop_index(op.f('ix_roadmap_progress_product_template_id'), table_name='roadmap_progress')
    op.drop_index(op.f('ix_roadmap_progress_id'), table_name='roadmap_progress')
    op.drop_index(op.f('ix_roadmap_progress_batch_id'), table_name='roadmap_progress')
    op.drop_table('roadmap_progress')
    op.drop_index(op.f('ix_product_recommendations_id'), table_name='product_recommendations')
    op.drop_index(op.f('ix_product_recommendations_batch_id'), table_name='product_recommendations')
    op.drop_table('product_recommendations')
    op.drop_index(op.f('ix_fermentation_logs_id'), table_name='fermentation_logs')
    op.drop_table('fermentation_logs')
    op.drop_index(op.f('ix_fermentation_batches_id'), table_name='fermentation_batches')
    op.drop_table('fermentation_batches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_product_templates_name'), table_name='product_templates')
    op.drop_index(op.f('ix_product_templates_id'), table_name='product_templates')
    op.drop_table('product_templates')
    # ### end Alembic commands ###
