"""Add image_url to fermentation_logs

Revision ID: f27716d2914e
Revises: 4fbe94f9e549
Create Date: 2026-07-30 19:00:37.354382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f27716d2914e'
down_revision: Union[str, Sequence[str], None] = '4fbe94f9e549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_progress_batch_id'), table_name='roadmap_progress')
    op.drop_index(op.f('ix_roadmap_progress_id'), table_name='roadmap_progress')
    op.drop_index(op.f('ix_roadmap_progress_product_template_id'), table_name='roadmap_progress')
    op.drop_index(op.f('ix_roadmap_progress_user_id'), table_name='roadmap_progress')
    op.drop_table('roadmap_progress')
    op.drop_index(op.f('ix_fermentation_logs_id'), table_name='fermentation_logs')
    op.drop_table('fermentation_logs')
    op.drop_index(op.f('ix_product_recommendations_batch_id'), table_name='product_recommendations')
    op.drop_index(op.f('ix_product_recommendations_id'), table_name='product_recommendations')
    op.drop_table('product_recommendations')
    op.drop_index(op.f('ix_product_templates_id'), table_name='product_templates')
    op.drop_index(op.f('ix_product_templates_name'), table_name='product_templates')
    op.drop_table('product_templates')
    op.drop_index(op.f('ix_fermentation_batches_id'), table_name='fermentation_batches')
    op.drop_table('fermentation_batches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('waste_diverted_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fermentation_batches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('waste_weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('water_liters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sugar_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('harvest_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('final_volume_liters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('final_aroma_intensity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fermentation_batches_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fermentation_batches_pkey'))
    )
    op.create_index(op.f('ix_fermentation_batches_id'), 'fermentation_batches', ['id'], unique=False)
    op.create_table('product_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processing_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('equipment', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('time_estimate_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('safety_warnings', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base_compatibility_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('product_templates_pkey'))
    )
    op.create_index(op.f('ix_product_templates_name'), 'product_templates', ['name'], unique=True)
    op.create_index(op.f('ix_product_templates_id'), 'product_templates', ['id'], unique=False)
    op.create_table('product_recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recommended_products_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('selected_product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('selection_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_commercial_orientation', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('business_analysis_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['fermentation_batches.id'], name=op.f('product_recommendations_batch_id_fkey')),
    sa.ForeignKeyConstraint(['selected_product_id'], ['product_templates.id'], name=op.f('product_recommendations_selected_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_recommendations_pkey'))
    )
    op.create_index(op.f('ix_product_recommendations_id'), 'product_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_product_recommendations_batch_id'), 'product_recommendations', ['batch_id'], unique=False)
    op.create_table('fermentation_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('log_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('aroma', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gas_presence', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('temperature_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ai_suggestion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['fermentation_batches.id'], name=op.f('fermentation_logs_batch_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fermentation_logs_pkey'))
    )
    op.create_index(op.f('ix_fermentation_logs_id'), 'fermentation_logs', ['id'], unique=False)
    op.create_table('roadmap_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_template_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('steps_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('current_step', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['fermentation_batches.id'], name=op.f('roadmap_progress_batch_id_fkey')),
    sa.ForeignKeyConstraint(['product_template_id'], ['product_templates.id'], name=op.f('roadmap_progress_product_template_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('roadmap_progress_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_progress_pkey'))
    )
    op.create_index(op.f('ix_roadmap_progress_user_id'), 'roadmap_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_roadmap_progress_product_template_id'), 'roadmap_progress', ['product_template_id'], unique=False)
    op.create_index(op.f('ix_roadmap_progress_id'), 'roadmap_progress', ['id'], unique=False)
    op.create_index(op.f('ix_roadmap_progress_batch_id'), 'roadmap_progress', ['batch_id'], unique=False)
    # ### end Alembic commands ###
